Cleaned up code, added dependancies check, added code comments.

diff --git a/usbswitch b/usbswitch
--- a/usbswitch
+++ b/usbswitch
@@ -4,6 +4,7 @@
 # Author: Eden Tyler-Moss https://github.com/ajmar
 # License: GNU GPLv3
 
+# Usage function to be called when the program is ran with -h
 usage () {
 	echo "# Usbswitch" 
 	echo -e "# Attach devices to and from a virtual machine\n"
@@ -21,83 +22,108 @@ usage () {
 	echo -e "\nSee https://github.com/ajmar/usbswitch for source & more details."
 }
 
+# Create an error function to be called for error message printing, printing in red.
 error () {
 	local CLR="\e[1;0m"
 	local RED="\e[1;31m"
 	printf "${RED}[ERROR]${CLR} %s${CLR}\n" "$@" 1>&2
 }
 
+# Check if the command has received any arguments, exit if not.
 [ "$#" = '0' ] && error "No arguments supplied." 1>&2 && exit 1
 
-list () {
-	echo "Number	ID	Name"
-	lsusb | cut -d " " -f 6- | cut -d ":" -f 2- | sed '/Linux Foundation/d' | sed 's/ /	/' | awk '{print NR-0 "	" $0}'
-}
-listvar="$(list)"
+# Check whether libvirt and lsusb are installed on the system.
+if ! (hash lsusb 2>/dev/null); then
+	error "lsusb is not installed." && exit 1
+elif ! (hash virsh 2>/dev/null); then
+	error "libvirt is not installed." && exit 1
+fi
+
+# Establishes a list of usb devices to be used, and removes Linux Foundation usb hubs.
 listfull="$(lsusb | cut -d " " -f 6- | sed '/Linux Foundation/d' | sed 's/ /	/' | awk '{print NR-0 "	" $0}')"
 
+# Tests whether there is multiple devices that the user could have meant, exits if so. If not, it creates a xml file for virsh to use, populating it with the usb device ids.
 select_device () {
 	if (( $(grep -c . <<<"$selectline") > 1 )); then
 		error "Device name not precise enough." 1>&2 && exit; fi
 	combined_id=$(echo "$selectline" | cut -d "	" -f 2- | cut -d "	" -f -1)
 	device_id=$(echo "$combined_id" | cut -d ":" -f 2-)
 	vendor_id=$(echo "$combined_id" | cut -d ":" -f -1)
-	printf "<hostdev mode='subsystem' type='usb' managed='no'>
+	echo "<hostdev mode='subsystem' type='usb' managed='no'>
 	<source>
-	<vendor id='0x"$vendor_id"'/>
-	<product id='0x"$device_id"'/>
+	<vendor id='0x$vendor_id'/>
+	<product id='0x$device_id'/>
 	</source>
 	</hostdev>" > /tmp/usbswitch.xml
 }
+
+# Tests whether the device input matches a usb device name, after testing id and number.
 select_name () {
 	selectline=$(echo "$listfull" | awk -F"	" '$3 ~ /'$OPTARG'/{print}')
-	[[ $selectline ]] && select_device || error "No matching device found." 1>&2 && exit
-}
-select_id () {
-	selectline=$(echo "$listfull" | awk -F"	" '$2 ~ /'$OPTARG'/{print}')
-	[[ $selectline ]] && select_device || select_name
-}
-select_num () { 
-	selectline=$(echo "$listfull" | awk -F"	" '$1 ~ /^'$OPTARG'$/{print}')
-	[[ $selectline ]] && select_device || select_id
+	[[ $selectline ]] && select_device || error "No matching device found." 1>&2 && exit 1
 }
 
+# Tests whether the device input matches a usb device id, after testing the number.
+select_id () {
+	selectline=$(echo "$listfull" | awk -F"	" '$2 ~ /'$OPTARG'/{print}')
+	if [[ $selectline ]]; then
+		select_device
+	else
+		select_name
+	fi
+}
+
+# Tests wether the device input matches a usb number.
+select_num () { 
+	selectline=$(echo "$listfull" | awk -F"	" '$1 ~ /^'$OPTARG'$/{print}')
+	if [[ $selectline ]]; then
+		select_device
+	else
+		select_id
+	fi
+}
+
+# First tests whether a device & domain has been specified, if the device is not already attached, and if the guest is running. If so, attach the device to the vm using the .xml file.
 attach_device () {
 	select_num &&
 	shift $((OPTIND - 1))
 	[ "$#" = 0 ] && error "Not enough arguments supplied." 1>&2 && exit 1
-	sudo virsh list --all | grep -E ""$1".*running" 1>/dev/null || (error "Is the guest running?"; exit 1)
-	printf 'Attaching:'"\n""$selectline""\n"
-	sudo virsh attach-device "$1" /tmp/usbswitch.xml 2>&1 | grep -q "is in use by" && error "Is the device already attached?" 1>&2 && exit 1 || exit
+	virsh list --all | grep -E "$1.*running" 1>/dev/null || (error "Is the guest running?"; exit 1)
+	virsh attach-device "$1" /tmp/usbswitch.xml 2>&1 | grep -q "is in use by" && error "Is the device already attached?" 1>&2 && exit 1 || echo -e 'Attaching:'"\n""$selectline" && exit
 }
 
+# First tests whether a device & domain has been specified, if the device is not already attached, and if the guest is running. If so, detach the device to the vm using the .xml file.
 detach_device () {
 	select_num &&
 	shift $((OPTIND - 1))
 	[ "$#" = 0 ] && error "Not enough arguments supplied." 1>&2 && exit 1
-	sudo virsh list --all | grep -E ""$1".*running" >/dev/null || (error "Is the guest running?"; exit 1)
-	printf 'Detaching:'"\n""$selectline""\n"
-	sudo virsh detach-device "$1" /tmp/usbswitch.xml 2>&1 | grep -q "error: device not found" && error "Is the device already detached?" 1>&2 && exit 1 || exit
+	virsh list --all | grep -E "$1.*running" >/dev/null || (error "Is the guest running?"; exit 1)
+	virsh detach-device "$1" /tmp/usbswitch.xml 2>&1 | grep -q "error: device not found" && error "Is the device already detached?" 1>&2 && exit 1 || echo -e 'Detaching:'"\n""$selectline" && exit
 }
 
+# First tests whether a device & domain has been specified, and if the device is not already in the domain. If so, add the device to the domain config using the .xml file.
 attach_device_perm () {
 	select_num &&
 	shift $((OPTIND - 1))
 	[ "$#" = 0 ] && error "Not enough arguments supplied." 1>&2 && exit 1
-	sudo virsh attach-device "$1" /tmp/usbswitch.xml --config 2>&1 | grep -q "device is already in the domain" && error "The device is already in the guest configuration." 1>&2 && exit 1 || printf 'Adding to config:'"\n""$selectline""\n" && exit
+	virsh attach-device "$1" /tmp/usbswitch.xml --config 2>&1 | grep -q "device is already in the domain" && error "The device is already in the guest configuration." 1>&2 && exit 1 || echo -e 'Adding to config:'"\n""$selectline" && exit
 }
 
+# First tests whether a device & domain has been specified, and if the device is in the domain. If so, remove the device from the domain config using the .xml file.
 detach_device_perm () {
 	select_num &&
 	shift $((OPTIND - 1))
 	[ "$#" = 0 ] && error "Not enough arguments supplied." 1>&2 && exit 1
-	sudo virsh detach-device "$1" /tmp/usbswitch.xml --config 2>&1 | grep -q "device not present in domain" && error "The device is not in the guest configuration." 1>&2 && exit 1 || printf 'Removing from config:'"\n""$selectline""\n" && exit
+	virsh detach-device "$1" /tmp/usbswitch.xml --config 2>&1 | grep -q "device not present in domain" && error "The device is not in the guest configuration." 1>&2 && exit 1 || echo -e 'Removing from config:'"\n""$selectline" && exit
 }
 
+# Uses getopts to detect specified options, and executes the relevant functions.
 while getopts ":la:d:t:A:D:T:h" opt; do
 	case "$opt" in
 		l)
-			list
+			echo "Number	ID	Name"
+			echo "$listfull"
+			exit
 			;;
 		a)
 			attach_device "${@}"
@@ -130,11 +156,11 @@ while getopts ":la:d:t:A:D:T:h" opt; do
 			usage && exit
 			;;
 		\?)
-			error "Invalid option: -"$OPTARG"" 1>&2
+			error "Invalid option: -$OPTARG" 1>&2
 			exit 1
 			;;
 		:)
-			error "-"$OPTARG" Requires an argument." 1>&2
+			error "-$OPTARG Requires an argument." 1>&2
 			exit 1
 			;;
 	esac
